In [2]:
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
df = pd.read_csv(r"C:\Users\MEGHARAJ1\OneDrive\cmprogram\Desktop\MachineLearning_Revise\Supervised_ML\cgpa_package_dataset.csv")

In [4]:
df.head()

   cgpa  package
0  6.69     5.68
1  9.28     8.47
2  8.29     7.61
3  7.69     6.56
4  5.70     6.06

In [14]:
x = df.drop("package", axis = "columns")
y = df["package"]

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [18]:
lr = LinearRegression()
lr.fit(x_train, y_train)
lr.score(x_train, y_train)*100, lr.score(x_test, y_test) * 100

(86.59007663695157, 80.73071676911763)

In [21]:
svr = SVR(kernel = "linear")
svr.fit(x_train, y_train)
svr.score(x_train, y_train) *100, svr.score(x_test, y_test) * 100

(86.50604199889074, 81.26640129904669)

In [23]:
dt = DecisionTreeRegressor()
dt.fit(x_train, y_train)
dt.score(x_train, y_train)*100, dt.score(x_test, y_test)*100

(98.85041817764346, 73.5602703081103)

In [25]:
li = [("dt", DecisionTreeRegressor()), ("SVR", SVR(kernel = "linear")), ("LR", LinearRegression())]

In [26]:
from sklearn.ensemble import VotingRegressor
vc = VotingRegressor(estimators = li)
vc.fit(x_train, y_train)
vc.score(x_train, y_train), vc.score(x_test, y_test)

(0.9339204031088482, 0.8011045384879858)

In [28]:
pred = {
    "DT" : dt.predict(x_test),
    "SVR" : svr.predict(x_test),
    "LR" : lr.predict(x_test),
    "VC" : vc.predict(x_test)
}

In [35]:
predict_df = pd.DataFrame(pred)

In [36]:
predict_df

       DT       SVR        LR        VC
0   5.880  6.548496  6.531209  6.319902
1   5.530  5.315708  5.264104  5.369937
2   7.370  7.000814  6.996119  7.122311
3   5.780  5.528563  5.482885  5.597149
4   4.280  4.606189  4.534834  4.473675
5   8.340  8.056222  8.080907  8.159043
6   9.130  8.517409  8.554932  8.734114
7   7.490  7.284621  7.287827  7.354149
8   7.510  7.151586  7.151089  7.270892
9   7.010  7.222538  7.224015  7.152184
10  5.240  5.138328  5.081786  5.153372
11  8.140  8.269077  8.299688  8.236255
12  8.360  7.914318  7.935053  8.069790
13  6.330  6.007488  5.975142  6.104210
14  7.850  7.843367  7.862126  7.851831
15  5.680  6.122785  6.093648  5.965477
16  5.000  4.934342  4.872122  4.935488
17  5.240  5.156066  5.100018  5.165361
18  6.145  5.901060  5.865751  5.970604
19  4.790  4.881128  4.817426  4.829518
20  4.960  5.493087  5.446421  5.299836
21  5.310  5.794632  5.756361  5.620331
22  4.260  4.783569  4.717152  4.586907
23  6.470  6.823434  6.813801  6.702412
24  5.970  6.743613  6.731759  6.481791
25  5.680  6.131654  6.102764  5.971472
26  5.790  5.821239  5.783708  5.798316
27  7.540  7.781284  7.798315  7.706533
28  6.430  6.282426  6.257733  6.323387
29  5.240  5.058507  4.999744  5.099417
30  7.390  7.408787  7.415449  7.404745
31  6.430  6.300164  6.275965  6.335376
32  8.140  8.260209  8.290572  8.230260
33  7.560  7.488607  7.497491  7.515366
34  8.370  8.206995  8.235877  8.270957
35  8.370  8.198126  8.226761  8.264962
36  5.960  5.865584  5.829288  5.884957
37  7.390  7.382180  7.388101  7.386760
38  5.000  4.943211  4.881237  4.941483
39  7.390  7.657118  7.670693  7.572604